<!-- Escribir la DTD que permita validar el documento XML que se muestra a continuación. Hacer dos versiones en cada caso: DTD externa e interna. 
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE lista_personas SYSTEM "lista_personas.dtd">
<lista_personas>
<persona>
<nombre>Antonio Moreno</nombre>
<fecha_nacimiento>27-11-2008</fecha_nacimiento>
<sexo>Varón</sexo>
</persona>
</lista_personas> -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_personas [
    <!ELEMENT lista_personas (persona)>
    <!ELEMENT persona (nombre, fecha_nacimiento,sexo)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fecha_nacimiento (#PCDATA)>
    <!ELEMENT sexo (#PCDATA)>
]>
<lista_personas>
      <persona>
      <nombre>Antonio Moreno</nombre>
      <fecha_nacimiento>27-11-2008</fecha_nacimiento>
      <sexo>Varón</sexo>
      </persona>
</lista_personas>