<!-- Escribir la DTD que permita validar el documento XML que se muestra a continuación. Hacer dos versiones en cada caso: DTD externa e interna. 
<lista_de_notas>
<nota>
<para>Pedro</para>
<de>Laura</de>
<titulo>Recordatorio</titulo>
<contenido>A las 7:00 pm en la puerta del teatro </contenido>
</nota>
<nota dia="23/01/2010" hora="13:15"> 
<para>Miguel</para> 
<de>Juan</de> 
<titulo>Informes</titulo> 
<contenido>Te he dejado los informes en el casillero</contenido> 
</nota> 
</lista_de_notas> -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula [
    <!ELEMENT matricula (personal, pago)+>
    <!ELEMENT personal (dni, nombre, titulacion, curso_academico, domicilios)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT titulacion (#PCDATA)>
    <!ELEMENT curso_academico (#PCDATA)>
    <!ELEMENT domicilios (domicilio+)>
    <!ATTLIST domicilio tipo (familiar|habitual) #REQUIRED>
    <!ELEMENT domicilio (nombre)>
    <!ELEMENT pago (tipo_matricula)>
    <!ELEMENT tipo_matricula (#PCDATA)>
]>
<matricula>
  <personal>
    <dni>99223366M</dni>
    <nombre>Juan Pardo Martín</nombre>
    <titulacion>Ingeniería Informática</titulacion>
    <curso_academico>1997/1998</curso_academico>
    <domicilios>
      <domicilio tipo="familiar">
        <nombre>C/ Principal nº1</nombre>
      </domicilio>
      <domicilio tipo="habitual">
        <nombre>C/ Secundaria nº2</nombre>
      </domicilio>
    </domicilios>
  </personal>
  <pago>
    <tipo_matricula>Matrícula Ordinaria</tipo_matricula>
  </pago>
</matricula>