=== ShadyX7/Lenguaje-de-Marcas/ACTIVIDADES/3 - TRIMESTRE/ENTREGA2_VICTOR_LOPEZ_3TRIMESTRE_MARCAS_DAM1/PRACTICA3/biblioteca.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT biblioteca (libro*)>
<!ELEMENT libro (codigo, titulo, Editorial, Edicion, ISBN,Numero_de_paginas, Autor)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT Editorial (#PCDATA)>
<!ELEMENT Edicion (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT EdiciÃ³n (#PCDATA)>
<!ELEMENT Numero_de_paginas (#PCDATA)>
<!ELEMENT Autor (#PCDATA)>

=== ShadyX7/Lenguaje-de-Marcas/ACTIVIDADES/3 - TRIMESTRE/ENTREGA2_VICTOR_LOPEZ_3TRIMESTRE_MARCAS_DAM1/PRACTICA3/PRACTICA3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>

<libro>
<codigo>777</codigo>
<titulo>Slim shady</titulo>
<Editorial>Casanova</Editorial>
<Edicion>Primera edición</Edicion>
<ISBN>58-58561-84-8</ISBN>
<Numero_de_paginas>350</Numero_de_paginas>
<Autor> Victor López</Autor>
</libro>

</biblioteca>
